const mockData = [
  [
    { stitch_type: "CO" },
    { stitch_type: "CO" },
    { stitch_type: "CO" },
    { stitch_type: "CO" },
    { stitch_type: "CO" },
    { stitch_type: "CO" },
    { stitch_type: "CO" },
    { stitch_type: "CO" },
    { stitch_type: "CO" },
    { stitch_type: "CO" },
    { stitch_type: "CO" },
    { stitch_type: "CO" },
    { stitch_type: "CO" },
    { stitch_type: "CO" },
    { stitch_type: "CO" },
    { stitch_type: "CO" },
    { stitch_type: "CO" },
  ],
  [
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "S" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
    { stitch_type: "P" },
    { stitch_type: "K" },
  ],
  [
    { stitch_type: "BO" },
    { stitch_type: "BO" },
    { stitch_type: "BO" },
    { stitch_type: "BO" },
    { stitch_type: "BO" },
    { stitch_type: "BO" },
    { stitch_type: "BO" },
    { stitch_type: "BO" },
    { stitch_type: "BO" },
    { stitch_type: "BO" },
    { stitch_type: "BO" },
    { stitch_type: "BO" },
    { stitch_type: "BO" },
    { stitch_type: "BO" },
    { stitch_type: "BO" },
    { stitch_type: "BO" },
    { stitch_type: "BO" },
  ],
];

const validate_matrix = (data) => {
  const colNum = data[0].length;
  for (const row of data) {
    if (row.length !== colNum) {
      return false;
    }
  }
  return true;
};

const add_x_y_pos = (data) => {
  if (!validate_matrix) {
    return false;
  }

  const dataWithCoordinates = data.map((row, rowIndex) => {
    for (const [colIndex, element] of row.entries()) {
      element["x_pos"] = colIndex + 1;
      element["y_pos"] = rowIndex + 1;
    }
    return row;
  });

  // const gridData = [];
  // gridData.push.apply(dataWithCoordinates);
  return dataWithCoordinates;
};

console.log(add_x_y_pos(mockData));
